### ISSUE TITLE
If there are multiple source requests inside a single test file they are merged together.

### ISSUE THREAD

**Issue by richardssam** [richardssam/ffmpeg-tests#26]
If I have 4 tests, each with their own image sources, then all 4 tests will end up using all the sources, not the source specified for the test.

[documentation_tests.zip](https://github.com/richardssam/ffmpeg-tests/files/9896655/documentation_tests.zip)

**Comment by apetrynet** [comment]
Thanks. I'll look into that.

**Comment by apetrynet** [comment]
I've located the bug. Working on a solution
